[package]
name = "rust_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_bindings"
crate-type = ["cdylib"]

[dependencies]
async-trait = { workspace = true }
pyo3 = "0.23.3"
tokio = { workspace = true }
chroma-log = { workspace = true }
chroma-system = { workspace = true }
