[package]
name = "chroma-sysdb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing-bunyan-formatter = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }

chroma-config = { workspace = true }
chroma-error = { workspace = true }
chroma-types = { workspace = true }
sqlx = { version = "0.8.3", features = [ "runtime-tokio",  "sqlite"] }
regex = "1.11.1"
sha2 = "0.10.8"
md5 = "0.7.0"

[dev-dependencies]
tempfile = { workspace = true }
