[workspace]

members = [
   "rust/blockstore",
   "rust/config",
   "rust/error", "rust/proto", "rust/storage",
   "rust/worker"
]

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
arrow = "52.0.0"
thiserror = "1.0.50"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
async-trait = "0.1.74"
roaring = "0.10.3"
futures = "0.3"
parking_lot = "0.12.1"
tracing = "0.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.7.10"
tonic = "0.10"
prost = "0.12"
prost-types = "0.12"

chroma-blockstore = { path = "rust/blockstore" }
chroma-error = { path = "rust/error" }
chroma-config = { path = "rust/config" }
chroma-storage = { path = "rust/storage" }
chroma-proto = { path = "rust/proto" }
worker = { path = "rust/worker" }

# Dev dependencies
"rand" = "0.8.5"
rand_xorshift = "0.3.0"
tempfile = "3.8.1"
shuttle = "0.7.1"
