[package]
name = "chroma"
version = "0.1.0"
edition = "2021"
description = "Placeholder for trychroma.com"
license = "Apache-2.0"

[dependencies]
sqlx = { workspace = true }
sha2 = { workspace = true }
md5 = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
