name: Start Tilt services
description: "This action starts Tilt services"
runs:
  using: "composite"
  steps:
    - name: Cache image layers
      id: cache
      uses: actions/cache@v4
      with:
        path: ./registry-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Install Tilt
      shell: bash
      run: |
        TILT_VERSION="0.33.3"
        curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v$TILT_VERSION/tilt.$TILT_VERSION.linux.x86_64.tar.gz | \
          tar -xzv -C /usr/local/bin tilt
    - name: Install ctlptlc
      shell: bash
      run: |
        CTLPTL_VERSION="0.8.20"
        curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v$CTLPTL_VERSION/ctlptl.$CTLPTL_VERSION.linux.x86_64.tar.gz | \
          tar -xzv -C /usr/local/bin ctlptl
    - name: Set up kind
      shell: bash
      run: ctlptl create cluster kind --registry=ctlptl-registry
    - name: Load cached image layers
      if: ${{ steps.cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        docker cp ./registry-cache "ctlptl-registry:/var/lib/registry"
    - name: Start Tilt
      shell: bash
      run: tilt ci
    - name: Export images to cache (if no cache hit)
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        docker cp "ctlptl-registry:/var/lib/registry" ./registry-cache
    - name: Forward ports
      shell: bash
      run: |
        # tilt ci does not forward ports
        # https://github.com/tilt-dev/tilt/issues/5964
        kubectl -n chroma port-forward svc/sysdb 50051:50051 &
        kubectl -n chroma port-forward svc/logservice 50052:50051 &
        kubectl -n chroma port-forward svc/query-service 50053:50051 &
        kubectl -n chroma port-forward svc/frontend-service 8000:8000 &
        kubectl -n chroma port-forward svc/minio 9000:9000 &
