name: Setup Rust
description: "This action sets up Rust"
inputs:
  sccache-token:
    description: "Auth token for sccache"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout chroma-hnswlib
      uses: actions/checkout@v4
      with:
        repository: chroma-core/hnswlib
        path: hnswlib
    # (actions/checkout doesn't allow cloning above the workspace root)
    - name: Symlink hnswlib to parent
      run: ln -s "$(pwd)/hnswlib" ../hnswlib
      shell: bash
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Setup Nextest
      uses: taiki-e/install-action@nextest
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
    - name: Set Rust caching env vars only on non-release runs
      shell: bash
      run: |
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
