[package]
name = "chroma-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
reqwest = "0.12.9"
semver = "1.0.26"
tokio = { workspace = true }
webbrowser = "1.0.3"

dialoguer = "0.11.0"
indicatif.workspace = true
sqlx = { workspace = true }

chroma-frontend = { workspace = true }
chroma-config = { workspace = true }
chroma-system = { workspace = true }
chroma-sqlite = { workspace = true }
chroma-segment = { workspace = true }
chroma-sysdb = { workspace = true }
chroma-types = { workspace = true }
chroma-log = { workspace = true }

[[bin]]
name = "chroma"
path = "src/main.rs"
