[package]
name = "chroma-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
webbrowser = "1.0.3"
tokio = { workspace = true }
colored = "3.0.0"
dialoguer = "0.11.0"
indicatif.workspace = true
sqlx = { workspace = true }

chroma-frontend = { workspace = true }
chroma-config = { workspace = true }
chroma-system = { workspace = true }
chroma-sqlite = { workspace = true }
chroma-segment = { workspace = true }
chroma-sysdb = { workspace = true }
chroma-types = { workspace = true }
chroma-log = { workspace = true }
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.20"
serde_json = { workspace = true }
dirs = "6.0.0"
reqwest = { workspace = true, features = ["blocking"] }
mockito = "1.7.0"
arboard = "3.4.1"


[[bin]]
name = "chroma"
path = "src/main.rs"
