[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "query_service"
path = "src/bin/query_service.rs"

[[bin]]
name = "compaction_service"
path = "src/bin/compaction_service.rs"

[[bench]]
name = "distance_metrics"
path = "src/benches/distance_metrics.rs"
harness = false

[dependencies]
rand = "0.8.5"
num_cpus = "1.16.0"
murmur3 = "0.5.2"
schemars = "0.8.16"
kube = { version = "0.87.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20.0", features = ["latest"] }
tantivy = "0.21.1"
tracing-bunyan-formatter = "0.3.3"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
opentelemetry = { version = "0.19.0", default-features = false, features = [
  "trace",
  "rt-tokio",
] }
opentelemetry-otlp = "0.12.0"
regex = "1.10.5"
flatbuffers = "24.3.25"
foyer = "0.8"

serde = { workspace = true }
serde_json = { workspace = true }
arrow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
roaring = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

chroma-blockstore = { workspace = true }
chroma-error = { workspace = true }
chroma-config = { workspace = true }
chroma-storage = { workspace = true }

[dev-dependencies]
proptest = "1.4.0"
proptest-state-machine = "0.1.0"
rayon = "1.8.0"
criterion = "0.3"
random-port = "0.1.1"
serial_test = "3.1.1"

"rand" = { workspace = true }
rand_xorshift = { workspace = true }
tempfile = { workspace = true }
shuttle = { workspace = true }

[build-dependencies]
cc = "1.0"
