[package]
name = "chroma-storage"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
aws-config = { version = "1.5", features = ["behavior-version-latest"] }
object_store = { version = "0.11", features = ["aws"] }

async-trait = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-types = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true}
serde = { workspace = true }
tempfile = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

chroma-config = { workspace = true }
chroma-error = { workspace = true }

[dev-dependencies]
rand_xorshift = { workspace = true }
