name: Go tests

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        platform: [depot-ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: chroma
          POSTGRES_PASSWORD: chroma
          POSTGRES_DB: chroma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/go
      - name: Build and test
        run: make test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        working-directory: go

  cluster-test:
    runs-on: "depot-ubuntu-22.04-16"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/go
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: (temp) build rust image
        run: |
          docker login registry.depot.dev -u x-token -p $DEPOT_TOKEN
          depot build --save --metadata-file build.json .
          project_id=$(cat build.json | jq -r '."depot.build".projectID')
          build_id=$(cat build.json | jq -r '."depot.build".buildID')

          echo "cached_image_ref=$project_id/$build_id" >> $GITHUB_ENV
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_PROJECT_TOKEN }}
      - uses: ./.github/actions/tilt
        with:
          cached-image-ref: ${{ env.cached_image_ref }}
      - run: bin/cluster-test.sh bash -c 'cd go && go test -timeout 30s -run ^TestNodeWatcher$ github.com/chroma-core/chroma/go/pkg/memberlist_manager'
      - name: Save service logs to artifact
        if: always()
        uses: ./.github/actions/export-tilt-logs
        with:
          artifact-name: "go-cluster-test"
