name: Rust tests

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        platform: [depot-ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
      CARGO_BUILD_JOBS: 16 # assume that most results are already cached, so we're I/O bound and not CPU bound
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/rust
        with:
          sccache-token: ${{ secrets.DEPOT_TOKEN }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo nextest run
  test-integration:
    strategy:
      matrix:
        platform: [depot-ubuntu-22.04-16]
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/rust
        with:
          sccache-token: ${{ secrets.DEPOT_TOKEN }}
      - name: Start services in Tilt
        uses: ./.github/actions/tilt
      - name: Run tests
        run: cargo nextest run --profile k8s_integration
      - name: Save service logs to artifact
        if: always()
        uses: ./.github/actions/export-tilt-logs
        with:
          artifact-name: "rust-integration-test"

  test-benches:
    strategy:
      matrix:
        platform: [depot-ubuntu-22.04-16]
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/rust
        with:
          sccache-token: ${{ secrets.DEPOT_TOKEN }}
      - name: Test compile
        run: cargo bench --no-run
